test_average (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... FAIL
test_to_degrees (__main__.TestExercice) ... ERROR
test_to_farenheit (__main__.TestExercice) ... ok
test_to_radians (__main__.TestExercice) ... ok

======================================================================
ERROR: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 56, in test_to_degrees
    output = [exercice.to_degrees(v) for v in values]
  File "test_exercice.py", line 56, in <listcomp>
    output = [exercice.to_degrees(v) for v in values]
  File "/home/runner/work/c01_ch3_exercices-Donphan29/c01_ch3_exercices-Donphan29/exercice.py", line 18, in to_degrees
    minutes = (deg - int(deg)) * 60
NameError: name 'deg' is not defined

======================================================================
FAIL: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 74, in test_to_celsius
    'Mauvais calcul de farenheit -> celsius'
AssertionError: Lists differ: [255.3722222222222, 241.48333333333332, 505.9277777777778] != [-17.77777777777778, -31.666666666666664, 232.77777777777777]

First differing element 0:
255.3722222222222
-17.77777777777778

- [255.3722222222222, 241.48333333333332, 505.9277777777778]
+ [-17.77777777777778, -31.666666666666664, 232.77777777777777] : Mauvais calcul de farenheit -> celsius

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1, errors=1)
